/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.lasarobotics.frc2017;

/**
 *
 * @author Gijs Landwehr
 */
public class fake_ds extends javax.swing.JFrame {

    /**
     * Creates new form fake_ds
     */
    public fake_ds() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        teleopButton = new javax.swing.JRadioButton();
        autonomousButton = new javax.swing.JRadioButton();
        testButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        enableButton = new javax.swing.JToggleButton();
        disableButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("hazy ds");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(102, 102, 255));
        setFocusable(false);
        setForeground(new java.awt.Color(153, 153, 255));
        setResizable(false);

        buttonGroup1.add(teleopButton);
        teleopButton.setSelected(true);
        teleopButton.setText("teleop");
        teleopButton.setFocusable(false);
        teleopButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                teleopButtonItemStateChanged(evt);
            }
        });

        buttonGroup1.add(autonomousButton);
        autonomousButton.setText("auto");
        autonomousButton.setFocusable(false);
        autonomousButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                autonomousButtonItemStateChanged(evt);
            }
        });

        buttonGroup1.add(testButton);
        testButton.setText("test");
        testButton.setFocusable(false);
        testButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                testButtonItemStateChanged(evt);
            }
        });

        jLabel1.setText("Mode");
        jLabel1.setFocusable(false);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 204));
        jLabel2.setText("hazy driver station");

        enableButton.setBackground(new java.awt.Color(0, 204, 51));
        buttonGroup2.add(enableButton);
        enableButton.setText("enabled");
        enableButton.setFocusable(false);
        enableButton.setOpaque(true);
        enableButton.setRolloverEnabled(false);
        enableButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                enableButtonStateChanged(evt);
            }
        });

        disableButton.setBackground(new java.awt.Color(255, 0, 51));
        buttonGroup2.add(disableButton);
        disableButton.setSelected(true);
        disableButton.setText("disabled");
        disableButton.setFocusable(false);
        disableButton.setOpaque(true);
        disableButton.setRolloverEnabled(false);
        disableButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                disableButtonItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enableButton)
                    .addComponent(disableButton))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(teleopButton)
                        .addComponent(autonomousButton)
                        .addComponent(testButton)))
                .addContainerGap(126, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addGap(109, 109, 109)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teleopButton)
                    .addComponent(enableButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(autonomousButton)
                    .addComponent(disableButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(testButton)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enableButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_enableButtonStateChanged
        if (enableButton.isSelected())
        {
            simrunner.setEnabled(true);
        }
    }//GEN-LAST:event_enableButtonStateChanged

    private void disableButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_disableButtonItemStateChanged
        if (disableButton.isSelected())
        {
            simrunner.setEnabled(false);
        }
    }//GEN-LAST:event_disableButtonItemStateChanged

    private void teleopButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_teleopButtonItemStateChanged
        if (teleopButton.isSelected())
        {
            simrunner.setTeleop();
        }
    }//GEN-LAST:event_teleopButtonItemStateChanged

    private void autonomousButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_autonomousButtonItemStateChanged
        if (autonomousButton.isSelected())
        {
            simrunner.setAutonomous();
        }
    }//GEN-LAST:event_autonomousButtonItemStateChanged

    private void testButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_testButtonItemStateChanged
        if (testButton.isSelected())
        {
            simrunner.setTest();
        }
    }//GEN-LAST:event_testButtonItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void runGUI() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fake_ds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fake_ds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fake_ds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fake_ds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fake_ds().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton autonomousButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JToggleButton disableButton;
    private javax.swing.JToggleButton enableButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton teleopButton;
    private javax.swing.JRadioButton testButton;
    // End of variables declaration//GEN-END:variables
}
